OUTPUT_PATH = "C:/SNIES_EXTRACTOR/outputs/"

LISTA_DIRECCIONES = [
        "C:/SNIES_EXTRACTOR/inputs/admitidos",
        "C:/SNIES_EXTRACTOR/inputs/graduados",
        "C:/SNIES_EXTRACTOR/inputs/inscritos",
        "C:/SNIES_EXTRACTOR/inputs/matriculados",
        "C:/SNIES_EXTRACTOR/inputs/matriculadosPrimerCurso"
    ]

STR_CODIGO_SNIES = "CÓDIGO SNIES DEL PROGRAMA"
STR_PROGRAMA_ACADEMICO = "PROGRAMA ACADÉMICO"
STR_METODOLOGIA = "METODOLOGÍA"
STR_NOMBRE_IES = "INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)"
STR_TIPO_IES = "PRINCIPAL O SECCIONAL"
STR_DEPARTAMENTO ="DEPARTAMENTO DE DOMICILIO DE LA IES"
STR_MUNICIPIO = "MUNICIPIO DE DOMICILIO DE LA IES"
STR_NIVEL_FORMACION = "NIVEL DE FORMACIÓN"
STR_SEMESTRE = "SEMESTRE"
STR_ADMITIDOS = "ADMITIDOS"
STR_GRADUADOS = "GRADUADOS"
STR_INSCRITOS = "INSCRITOS"
STR_MATRICULADOS = "MATRICULADOS"
STR_PRIMER_CURSO = "PRIMER CURSO"