name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Cambia la versión según tu proyecto

    - name: Install dependencies
      run: |
        python -m venv venv  # Crear un entorno virtual
        source venv/bin/activate  # Activar el entorno virtual
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar dependencias desde el archivo

    - name: Run tests
      run: |
        source venv/bin/activate  # Asegurarse de que el entorno virtual esté activo